### ISSUE TITLE
python import script - compatible with levels?

### ISSUE THREAD

**Issue by mccollek** [goinvo/Visual-Town-Budget#26]
trying to use 'processCSV.py' with a csv file (first two lines below). getting the following error:

@Expenses
list index out of range
Error reconstructing tree at node: <__main__.entry instance at 0x7f9edeafccb0>

==========CSV Example=================================
LEVEL1,LEVEL2,LEVEL3,LEVEL4,LEVEL5,TOOLTIP,SOURCE,SOURCE URL,2010,2011,2012,2013,2014,2015,2016,2017,2018,LEVEL
General Fund,Administration,SALARIES AND WAGES,,,,,,104357.00,111563.00,179844.00,115976.00,222554.00,160906.00,,,,3

**Comment by BenjaminListwon** [comment]
Hi Karl,

Do you have the entire traceback handy?

**Comment by mccollek** [comment]
-> import csv, json, hashlib, zlib, sys, os
Traceback (most recent call last):
  File "/usr/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/usr/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "processCSV.py", line 1, in <module>
    import csv, json, hashlib, zlib, sys, os
  File "processCSV.py", line 1, in <module>
    import csv, json, hashlib, zlib, sys, os
  File "/usr/lib/python2.7/bdb.py", line 49, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/lib/python2.7/bdb.py", line 67, in dispatch_line
    self.user_line(frame)
  File "/usr/lib/python2.7/pdb.py", line 158, in user_line
    self.interaction(frame, None)
  File "/usr/lib/python2.7/pdb.py", line 210, in interaction
    self.cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 130, in cmdloop
    line = raw_input(self.prompt)
ValueError: I/O operation on closed file
(Pdb) Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /usr/lib/python2.7/cmd.py(130)cmdloop()
-> line = raw_input(self.prompt)
(Pdb) Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/pdb.py", line 1338, in <module>
    pdb.main()
  File "/usr/lib/python2.7/pdb.py", line 1330, in main
    pdb.interaction(None, t)
  File "/usr/lib/python2.7/pdb.py", line 210, in interaction
    self.cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 130, in cmdloop
    line = raw_input(self.prompt)
ValueError: I/O operation on closed file

**Comment by BenjaminListwon** [comment]
Hi Karl,

Looks like it is bombing out in the course of normal iteration over the lines from the CSV. cmdloop is module that helps facilitate iteration line by line.

My initial suspicion was that the line it is choking on has an mismatch in the number of commas, with the count found in the header. Thus producing an index that is past the end of available values. 

This can sometimes happen if there is a string that should have been a quoted string that contains a comma as apt of its value. It also occurs from time to time if there are empty rows at the end of the file that get prematurely clipped, or are blank.

The only real way for me to tell would be to examine the CSV itself. However, if you're not able to share it, you could do some quick and dirty debugging by adding a print statement at line 65: `print(dataline)`

Since it is a dict, you may want to `import pprint` up at the top and use `pprint.pprint(dataline)` instead.

If you'd like me to take a look at the file, just let me know where to go.

**Comment by mccollek** [comment]
It's actually choking on the last line:

{'2010': '0.00',
 '2011': '0.00',
 '2012': '0.00',
 '2013': '0.00',
 '2014': '',
 '2015': '0.00',
 '2016': '',
 '2017': '',
 '2018': '',
 'LEVEL': '3',
 'LEVEL1': 'General Fund',
 'LEVEL2': 'Other Expenditures',
 'LEVEL3': '"TO GENERAL FUND"',
 'LEVEL4': '',
 'LEVEL5': '',
 'SOURCE': '',
 'SOURCE URL': '',
 'TOOLTIP': ''}
{'2010': '',
 '2011': '86633.00',
 '2012': '0.00',
 '2013': '0.00',
 '2014': '0.00',
 '2015': '0.00',
 '2016': '',
 '2017': '',
 '2018': '',
 'LEVEL': '3',
 'LEVEL1': 'General Fund',
 'LEVEL2': 'Other Expenditures',
 'LEVEL3': '"TO TOUR/ST ACCOM/FR GEN FUND"',
 'LEVEL4': '',
 'LEVEL5': '',
 'SOURCE': '',
 'SOURCE URL': '',
 'TOOLTIP': ''}
@Expenses
list index out of range
Error reconstructing tree at node: <__main__.entry instance at 0x7f9be7ed1ab8>

**Comment by mccollek** [comment]
I added a 

	for node in csventries:
            pprint.pprint(node.key)

looks like it's actually failing on the trying to parse last has before (@Expenses)..... is it have problems escaping the forward-slashes?

**Comment by BenjaminListwon** [comment]
It's possible. I'll run a few tests in about an hour and let you know. If it is the slashes, I'll add a fix as well.

**Comment by BenjaminListwon** [comment]
Hi Karl,

There's a bit of a bug/assumption in the script where it only runs if the last line is the TOTAL line, as seen in the reference CSV files. 

Basically the tree traversal code relies on the last line ending with a LEVEL value of 0.

You *could* make a fake row just to see it work, like `,,,,,,,,,,,,,,,,,0` 

But there is another downside to not having a totals row. The code does not compute totals for display on the initial view of the the card presented alongside the treemap, it pulls those values from that line in the CSV that contains precomputed total values. 

It is therefore best to run a quick SUM on the CSV columns and generate a totals row similar to one in any of the source files.

Hope that helps.

I'll think through a solution that checks for a total row, and if it is not present, maybe computes one for you. In the meantime, I'll throw a better error in there when that row is not present.

**Comment by mccollek** [comment]
Thanks!

**Comment by mccollek** [comment]
Hi Benjamin!  I now have total columns, but I'm stilling getting an error.  I've pasted a truncated version of the file below.

Thanks,
Karl


LEVEL1,LEVEL2,LEVEL3,LEVEL4,LEVEL5,TOOLTIP,SOURCE,SOURCE URL,2010,2011,2012,2013,2014,2015,2016,LEVEL
Accomodations Fees,"""TO TOURISM""",,,,,,,140000.00,140000.00,140000.00,140000.00,140000.00,140000.00,,2
Accomodations Fees,"""TO GENERAL FUND QOL PROJ""",,,,,,,65000.00,67971.00,106361.00,141562.00,143000.00,155483.00,,2
Accomodations Fees,"""QUALITY OF LIFE BUDG PROJ""",,,,,,,0.00,0.00,56339.00,73438.00,93000.00,82517.00,,2
Accomodations Fees,"""PROJECT EXPENSES""",,,,,,,32812.00,0.00,0.00,0.00,0.00,0.00,,2
Accomodations Fees,"""PROJECT EXPENSES""",,,,,,,,,,,,15000.00,,2
Accomodations Fees,"""PROJECT EXPENSES CULTURE""",,,,,,,,,,,,,,2
Accomodations Fees,"""PROJECT EXPENSES CULTURE""",,,,,,,0.00,525.00,130016.00,0.00,0.00,0.00,,2
Accomodations Fees,"""OTHER/PROJECT EXPENSES""",,,,,,,,,,,,,,2
Accomodations Fees,"""IMPRV OTHER THAN BLDINGS""",,,,,,,1200.00,45808.00,0.00,0.00,0.00,0.00,,2
Accomodations Fees,"""ADVERTISING/PROJ EXP DOWNTOWN""",,,,,,,32399.00,42332.00,61300.00,20000.00,32000.00,32000.00,,2
Accomodations Fees,"","","","","","","",271411.0,296636.0,494016.0,375000.0,408000.0,425000.0,0,1
TOTAL,"","","","","","","",50108834.74,50350479.0,55715260.0,55226620.0,57273292.809999995,60510156.960000016,22309548.66,0

**Comment by mccollek** [comment]
Stack trace: <__main__.entry instance at 0x7fcfc58f90e0>
'Expenses2'
@Expenses2
list index out of range
Error reconstructing tree at node: <__main__.entry instance at 0x7fcfc58f90e0>
The program exited via sys.exit(). Exit status:  1
> /home/mccollek/Workspace/visual-town-budget/src/httpdocs/data/processing/processCSV.py(1)<module>()
-> import csv, json, hashlib, zlib, sys, os, pprint
Traceback (most recent call last):
  File "/usr/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/usr/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "processCSV.py", line 1, in <module>
    import csv, json, hashlib, zlib, sys, os, pprint
  File "processCSV.py", line 1, in <module>
    import csv, json, hashlib, zlib, sys, os, pprint
  File "/usr/lib/python2.7/bdb.py", line 49, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/lib/python2.7/bdb.py", line 67, in dispatch_line
    self.user_line(frame)
  File "/usr/lib/python2.7/pdb.py", line 158, in user_line
    self.interaction(frame, None)
  File "/usr/lib/python2.7/pdb.py", line 210, in interaction
    self.cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 130, in cmdloop
    line = raw_input(self.prompt)
ValueError: I/O operation on closed file
(Pdb) Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /usr/lib/python2.7/cmd.py(130)cmdloop()
-> line = raw_input(self.prompt)
(Pdb) Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/pdb.py", line 1338, in <module>
    pdb.main()
  File "/usr/lib/python2.7/pdb.py", line 1330, in main
    pdb.interaction(None, t)
  File "/usr/lib/python2.7/pdb.py", line 210, in interaction
    self.cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 130, in cmdloop
    line = raw_input(self.prompt)
ValueError: I/O operation on closed file

**Comment by BenjaminListwon** [comment]
Hi Karl,

I just ran it on that truncated file example you pasted and it ran okay. I also cloned a fresh copy of the repository to make sure I was working off the same source.

I did notice one thing though, that might be making trouble for you, versus on my machine. There are a couple of large floating point numbers in your totals row: 

`57273292.809999995,60510156.960000016`

It is possible that, if you're running on a different architecture than mine, those numbers are too big for the available float size.

Why not try a rounded totals line like this in your file:

`TOTAL,"","","","","","","",50108834.74,50350479.0,55715260.0,55226620.0,57273292.81,60510156.96,22309548.66,0`

**Comment by mccollek** [comment]
Thanks!  I pulled down the updates and it ran like a charm.



On Thu, Mar 19, 2015 at 5:03 PM, Benjamin Listwon <notifications@github.com>
wrote:

> Hi Karl,
>
> I just ran it on that truncated file example you pasted and it ran okay. I
> also cloned a fresh copy of the repository to make sure I was working off
> the same source.
>
> I did notice one thing though, that might be making trouble for you,
> versus on my machine. There are a couple of large floating point numbers in
> your totals row:
>
> 57273292.809999995,60510156.960000016
>
> It is possible that, if you're running on a different architecture than
> mine, those numbers are too big for the available float size.
>
> Why not try a rounded totals line like this in your file:
>
>
> TOTAL,"","","","","","","",50108834.74,50350479.0,55715260.0,55226620.0,57273292.81,60510156.96,22309548.66,0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/goinvo/Visual-Town-Budget/issues/26#issuecomment-83759643>
> .
>



-- 
Karl McCollester
1301 Gervais St.
Suite 200
Columbia, SC 29201
www.udhaa.com
803-250-1301
Need to meet?: https://calendly.com/mckarl
<https://via.intercom.io/c?url=https%3A%2F%2Fcalendly.com%2Fmckarl&h=6a043dd2f6f2b7761f1153dc8dc05b7e2f213529-726201222>
